all: app.exe

app.exe:
	g++ main.cpp Set.cpp BaseSet.cpp ConstIterator.cpp BaseIterator.cpp SetExceptions.hpp -o main.exe
debug:
	g++ -g main.cpp Set.cpp BaseSet.cpp ConstIterator.cpp BaseIterator.cpp SetExceptions.hpp -o main.exe